BookLibrary/BookLibrary/Models/User.cs
namespace BookLibrary.Models
{
    public class User
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Role Role { get; set; }
        public bool IsLogged { get; set; }

        public User(int id, string email, string password, Role role)
        {
            Id = id;
            Email = email;
            Password = password;
            Role = role;
            IsLogged = false;
        }

        public User()
        {

        }
    }
}

BookLibrary/BookLibrary/ViewModels/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BookLibrary.ViewModels
{
    public class UserViewModel
    {
        [Required]
        public string Email { get; set; }
        [Required]
        public string Password { get; set; }
    }
}

BookLibrary/BookLibrary/Controllers/LoanController.cs
using BookLibrary.Models;
using BookLibrary.Services;
using BookLibrary.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;

namespace BookLibrary.Controllers
{
    public class LoanController : Controller
    {
        private readonly IUserService _userService;
        private readonly IBookService _bookService;
        private readonly ILoanService _loanService;
        public LoanController(IUserService userService,IBookService bookService, ILoanService loanService)
        {
            _userService = userService;
            _bookService = bookService;
            _loanService = loanService;
        }

        public IActionResult Index()
        {
            var loans = new LoanListViewModel();
            return View(loans);
        }

        [HttpGet]
        public IActionResult LoanBooks()
        {
            var loan = new LoanViewModel();
            return View(loan);
        }

        [HttpPost]
        public IActionResult LoanBooks(LoanViewModel model)
        {
            var bookIsAvailable = _loanService.CheckIfBookIsAvailable(model.SelectedBook);
            var userHasTheBook = _loanService.CheckIfUserHasTheBook(model.SelectedBook);
            var moreThan5 = _loanService.LoanedMoreThan5();
            if (!bookIsAvailable)
            {
                ModelState.AddModelError("CustomError", "The book isn't available.Please select another book.");
                return View(model);

            }else if (userHasTheBook)
            {
                ModelState.AddModelError("CustomError", "You have already loaned the book that you have selected.Please select another book.");
                return View(model);
            }else if (moreThan5)
            {
                ModelState.AddModelError("CustomError", "You have already loaned 5 Books. Please return one book so you can loan new book.");
                return View(model);
            }
            _loanService.CreateLoan(model);
            return RedirectToAction("LogIn", "User");
        }

        [HttpGet]
        public IActionResult ReturnBook(int id)
        {
            _loanService.ReturnBook(id);
            return RedirectToAction("LogIn", "User");
        }
    }
}

BookLibrary/BookLibrary/Controllers/UserController.cs
using BookLibrary.Models;
using BookLibrary.Services;
using BookLibrary.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace BookLibrary.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly ILoanService _loanService;
        public UserController(IUserService userService, ILoanService loanService)
        {
            _userService = userService;
            _loanService = loanService;
        }

        [HttpGet]
        public IActionResult LogIn()
        {
            if (_userService.CheckIfSomeoneIsLogged())
            {
                var foundUser = _userService.FindLoggedUser();
                ViewBag.ActiveLoans = _loanService.ListAllLoans().Where(x => x.User == foundUser && x.Status == LoanStatusEnum.Active);
                ViewBag.PastLoans = _loanService.ListAllLoans().Where(x => x.User == foundUser && x.Status == LoanStatusEnum.Finished);
                return View("ShowUser", foundUser);
            }
            UserViewModel user = new UserViewModel();
            return View(user);
        }

        [HttpPost]
        public IActionResult ShowUser(UserViewModel model)
        {
            User user = _userService.ChangeToModel(model);
            var foundUser = _userService.FindUser(user);
            if(foundUser == null)
            {
                ModelState.AddModelError("CustomError", "The user name or password is incorrect");
                return View("LogIn", model);
            }
            foundUser.IsLogged = true;
            ViewBag.ActiveLoans = _loanService.ListAllLoans().Where(x => x.User == foundUser && x.Status == LoanStatusEnum.Active);
            ViewBag.PastLoans = _loanService.ListAllLoans().Where(x => x.User == foundUser && x.Status == LoanStatusEnum.Finished);
            return View(foundUser);
        }

        [HttpGet]
        public IActionResult LogOut(int id)
        {
            User user = _userService.GetUserById(id);
            user.IsLogged = false;
            return RedirectToAction("LogIn", "User");
        }

        [HttpGet]
        public IActionResult ChangePassword()
        {
            var newUser = new User();
            return View(newUser);
        }

        [HttpPost]
        public IActionResult ChangePassword(User user)
        {
            var loggedUser = _userService.FindLoggedUser();
            user.Id = loggedUser.Id;
            user.Email = loggedUser.Email;
            user.IsLogged = loggedUser.IsLogged;
            user.Role = loggedUser.Role;
            _userService.UpdateExisting(user);
            return View("ShowUser",user);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var user = new UserViewModel();
            return View(user);
        }

        [HttpPost]
        public IActionResult Create(UserViewModel model)
        {
            var loggedUser = _userService.FindLoggedUser();
            _userService.RegisterUser(model);
            if(loggedUser != null)
            {
                return RedirectToAction("LogOut", new { id = loggedUser.Id });
            }
            return RedirectToAction("LogIn");
        }
    }
}

BookLibrary/BookLibrary/Views/User/ChangePassword.cshtml
@model  BookLibrary.Models.User
@{
    ViewData["Title"] = "ChangePassword";
}

<h2>ChangePassword</h2>

<form asp-action="ChangePassword" asp-controller="User">
    <h2 class="text-center">Change Password</h2>
    <div class="form-group">
        <label asp-for="Password" class="control-label">New Password:</label>
        <input asp-for="Password" class="form-control" />
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>

BookLibrary/BookLibrary/Views/User/Create.cshtml
@model  BookLibrary.ViewModels.UserViewModel
@{
    ViewData["Title"] = "Create";
}

<h2>Register</h2>

<div class="row">
    <div class="col-md-6">
        <form asp-action="Create" asp-controller="User">
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <input type="submit" value="Create" class="btn btn-primary" />
        </form>
    </div>
</div>

BookLibrary/BookLibrary/Views/User/LogIn.cshtml
@model  BookLibrary.ViewModels.UserViewModel
@{
    ViewData["Title"] = "LogIn";
}

<div class="row">
    <div class="col-4"></div>
    <div class="col-4"> 
        <form asp-action="ShowUser" asp-controller="User">
            <h2 class="text-center">Log in</h2>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
                @Html.ValidationMessage("CustomError",new { @class = "text-danger"})
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Log In" class="btn btn-primary btn-block" />
            </div>
            <div class="form-group">
                <a asp-action="Create" asp-controller="User">Register</a>
            </div>
        </form>
    </div>
    <div class="col-4"></div>
</div>

BookLibrary/BookLibrary/Views/User/ShowUser.cshtml
@model BookLibrary.Models.User
@{
    ViewData["Title"] = "UserProfile";

}

<h2>My Account</h2>
<hr />
<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.Email)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Email)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Password)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Password) 
        <a asp-action="ChangePassword" asp-controller="User" asp-route-id="@Model.Id">Change Password</a>
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Role.Name)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Role.Name)
    </dd>
</dl>
<a asp-action="LoanBooks" asp-controller="Loan" asp-route-id="@Model.Id" class="btn btn-primary">Loan Book</a>
<a asp-action="LogOut" asp-controller="User" asp-route-id="@Model.Id" class="btn btn-danger">Log Out</a>
<br />
<br />
<h2><span class="badge badge-success">Active Loans</span></h2>
<table class="table">
    <thead>
        <tr>
            <th>Book</th>
            <th>Loan Date</th>
            <th>Date You Need To Return</th>
            <th>Date Returned</th>
            <th>Status</th>
            <th>Return Book</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var loan in ViewBag.ActiveLoans)
            {
                <tr>
                    <td>@loan.Book.Name</td>
                    <td>@loan.LoanDate.ToString()</td>
                    <td>@loan.LoanDate.AddDays(30).ToString()</td>
                    <td>@loan.DateReturned</td>
                    <td>@loan.Status.ToString()</td>
                    <td><a asp-action="ReturnBook" asp-controller="Loan" asp-route-id="@loan.Id">Return Book</a></td>
                </tr>
            }
        }
    </tbody>
</table>
<br />
<br />
<h2><span class="badge badge-success">Past Loans</span></h2>
<table class="table">
    <thead>
        <tr>
            <th>Book</th>
            <th>Loan Date</th>
            <th>Date Returned</th>
            <th>Status</th>
            <th>Fine Paid</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var loan in ViewBag.PastLoans)
            {
                <tr>
                    <td>@loan.Book.Name</td>
                    <td>@loan.LoanDate.ToString()</td>
                    <td>@loan.DateReturned</td>
                    <td>@loan.Status.ToString()</td>
                    <td>@loan.FinePaid</td>
                </tr>
            }
        }
    </tbody>
</table>